#!/usr/bin/env ruby
#
# Usage: check_zips <csv-file>
#
# This will check that the zip in the zipcode field matches the one in the
# gmap_addr field.  Any differences will be printed out with a line number.


if ARGV.length != 1
  puts "Usage: check_zips <csv-file>"
  exit 1
end
File.open(ARGV[0]) { |f|
  f.readlines.each_with_index { |line,n|
    next if n == 0 || line =~ /^\s*$/

    toks = line.split(",")
    zip1 = toks[5]
    zip2 = toks[-2]
    zip2.sub!(/^ TX /, "")

    if zip1 != zip2.slice(0,5)
      puts "#{n+1}: #{zip1} #{zip2.slice(0,5)}"
    end
  }
}
