--BROWNSBORO
SELECT 
"STUDENT_ATND_DETAIL"."ATND-DATE" AS 'ABSENCEDATE',
'107902'+"ENTITY"."ENTITY-ID" AS 'CAMPUSID',
"ENTITY"."ENTITY-NAME" AS 'SCHOOLNAME',

count("STUDENT_ATND_DETAIL"."STUDENT-ID") as 'ABSENT'
FROM   "SKYWARD"."PUB"."STUDENT-ATND-DETAIL" "STUDENT_ATND_DETAIL"
INNER JOIN  "SKYWARD"."PUB"."ENTITY" ON
"STUDENT_ATND_DETAIL"."ENTITY-ID" = "ENTITY"."ENTITY-ID" AND
"STUDENT_ATND_DETAIL"."SCHOOL-YEAR" = "ENTITY"."SCHOOL-YEAR"

WHERE  "STUDENT_ATND_DETAIL"."ATND-DATE" <= Curdate() and
 ("STUDENT_ATND_DETAIL"."AAT-ID"[1] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
)or
"STUDENT_ATND_DETAIL"."AAT-ID"[2] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[3] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[4] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[5] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[5] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[6] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[7] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[8] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[9] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[10] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[11] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
) OR
"STUDENT_ATND_DETAIL"."AAT-ID"[12] in 
(
 SELECT "ATND_ABSENCE_TYPE"."AAT-ID"
 FROM   "SKYWARD"."PUB"."ATND-ABSENCE-TYPE" "ATND_ABSENCE_TYPE"
 WHERE  
     "ATND_ABSENCE_TYPE"."AAT-EXC-UNEXC-TAR-OTH"<>'T' AND
     "ATND_ABSENCE_TYPE"."ENTITY-ID"="STUDENT_ATND_DETAIL"."ENTITY-ID" AND
     "ATND_ABSENCE_TYPE"."AAT-INCL-IN-TOT-ATND"=1 and
     "ATND_ABSENCE_TYPE"."SCHOOL-YEAR"="STUDENT_ATND_DETAIL"."SCHOOL-YEAR"
)
)
GROUP BY "ENTITY"."ENTITY-ID",
"ENTITY"."ENTITY-NAME",
"STUDENT_ATND_DETAIL"."ATND-DATE"
