--BROWNSBORO
SELECT
SYSDATE() AS 'ENROLLDATE',
'107902'+"STUDENT_EW"."ENTITY-ID" AS 'CAMPUSID',
' ' AS 'SCHOOLNAME',
count( "STUDENT_EW"."STUDENT-ID") AS 'CURRENT_ENROLLMENT'

FROM   "SKYWARD"."PUB"."STUDENT-EW" "STUDENT_EW" 
 WHERE  "STUDENT_EW"."EW-DATE"<=SYSDATE() AND ("STUDENT_EW"."WITHDRAWAL-DATE" IS  NULL  OR "STUDENT_EW"."WITHDRAWAL-DATE">SYSDATE())
GROUP BY "STUDENT_EW"."ENTITY-ID"
